[server]
bind = "127.0.0.1"
port = "9590"
error_log = "./oasis.log"
access_log = "./access.log"

[mysql]
user = "oasis"
host = "127.0.0.1"
port = "3306"
password = "eQWJjZGV1A(MjAxOQo"
database = "oasis"


